services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:12
    environment:
      SHARED_DIRECTORY: /srv/luma
    volumes:
    - /srv/luma:/srv/luma
    - /lib/modules:/lib/modules:ro
    ports:
    - target: 2049
      published: 2049
      protocol: tcp
      mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.luma.node.name == manager-host
    cap_add:
    - SYS_ADMIN
    - SETPCAP
