FROM grafana/grafana:11.5.2
USER root
COPY grafana/provisioning /etc/grafana/provisioning
COPY grafana/dashboards /var/lib/grafana/dashboards
RUN grafana-cli --pluginsDir /var/lib/grafana/plugins plugins install victoriametrics-logs-datasource \
    && chown -R grafana:root /etc/grafana/provisioning /var/lib/grafana/dashboards /var/lib/grafana/plugins
USER grafana
