import type { ComposeDeploymentDraft, DeployTemplate, ServiceManifestDraft } from "./types";

let rowCounter = 0;
const row = (key = "", value = "") => ({ id: `row-${rowCounter++}`, key, value });

export function serviceDraft(overrides: Partial<ServiceManifestDraft> = {}): ServiceManifestDraft {
  return {
    name: "whoami",
    image: "traefik/whoami:latest",
    region: "cn",
    node: "",
    exposure: "cn-edge",
    domain: "whoami.example.com",
    port: "80",
    publishPort: "",
    replicas: 1,
    proxy: false,
    env: [],
    command: "",
    labels: "",
    networks: "",
    volumes: "",
    cpuLimit: "",
    memoryLimit: "",
    healthcheckUrl: "",
    skipDns: false,
    skipWebhook: false,
    ...overrides,
  };
}

function composeDraft(overrides: Partial<ComposeDeploymentDraft> = {}): ComposeDeploymentDraft {
  return {
    name: "uptime-kuma",
    composeFileName: "docker-compose.yml",
    region: "home",
    services: [],
    volumes: [],
    dockerComposeYaml: "",
    skipDns: false,
    skipWebhook: false,
    ...overrides,
  };
}

export const DEPLOY_TEMPLATES: DeployTemplate[] = [
  {
    id: "service-custom",
    mode: "service",
    name: "自定义配置",
    description: "从空白配置开始创建单服务。",
    tags: ["custom", "blank"],
    service: serviceDraft({
      name: "",
      image: "",
      domain: "",
      port: "",
      exposure: "none",
    }),
  },
  {
    id: "compose-custom",
    mode: "compose",
    name: "自定义配置",
    description: "从空白配置开始创建 Compose 应用。",
    tags: ["custom", "blank"],
    compose: composeDraft({
      name: "",
      services: [],
      volumes: [],
      dockerComposeYaml: [
        "services:",
        "  # 在此编写您的 docker-compose 服务",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "service-whoami",
    mode: "service",
    name: "whoami",
    description: "最小 HTTP 探针服务，用来验证 DNS、Traefik 和调度。",
    tags: ["test", "cn-edge"],
    service: serviceDraft(),
  },
  {
    id: "service-nginx",
    mode: "service",
    name: "nginx",
    description: "公开静态 Web 服务模板，适合快速验证入口。",
    tags: ["web", "public"],
    service: serviceDraft({
      name: "nginx",
      image: "nginx:alpine",
      domain: "nginx.example.com",
      healthcheckUrl: "http://127.0.0.1:80/",
      cpuLimit: "0.50",
      memoryLimit: "256M",
    }),
  },
  {
    id: "service-redis-worker",
    mode: "service",
    name: "redis worker",
    description: "内部 Redis 服务，不公开入口，可作为 worker/internal 示例。",
    tags: ["internal", "state"],
    service: serviceDraft({
      name: "redis",
      image: "redis:7-alpine",
      exposure: "none",
      domain: "",
      port: "",
      env: [row("REDIS_ARGS", "--appendonly yes")],
      volumes: "redis-data:/data",
      memoryLimit: "256M",
    }),
  },
  {
    id: "compose-uptime-kuma",
    mode: "compose",
    name: "Uptime Kuma",
    description: "自托管监控面板，默认通过 home relay 暴露。",
    tags: ["monitoring", "stateful"],
    compose: composeDraft({
      name: "uptime-kuma",
      region: "home",
      services: [{ name: "uptime-kuma", region: "home", node: "", exposure: "tailscale-relay", domain: "kuma.example.com", port: "3001", publishPort: "", replicas: 1, proxy: false }],
      volumes: [{ name: "kuma-data", target: "/app/data", storageMode: "storageClass", storageClass: "", localNode: "", localPath: "" }],
      dockerComposeYaml: [
        "services:",
        "  uptime-kuma:",
        "    image: louislam/uptime-kuma:1",
        "    volumes:",
        "      - kuma-data:/app/data",
        "volumes:",
        "  kuma-data: {}",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "compose-vaultwarden",
    mode: "compose",
    name: "Vaultwarden",
    description: "轻量密码库，建议使用已注册 storageClass。",
    tags: ["security", "stateful"],
    compose: composeDraft({
      name: "vaultwarden",
      region: "home",
      services: [{ name: "vaultwarden", region: "home", node: "", exposure: "tailscale-relay", domain: "vault.example.com", port: "80", publishPort: "", replicas: 1, proxy: false }],
      volumes: [{ name: "vaultwarden-data", target: "/data", storageMode: "storageClass", storageClass: "", localNode: "", localPath: "" }],
      dockerComposeYaml: [
        "services:",
        "  vaultwarden:",
        "    image: vaultwarden/server:latest",
        "    environment:",
        "      WEBSOCKET_ENABLED: \"true\"",
        "    volumes:",
        "      - vaultwarden-data:/data",
        "volumes:",
        "  vaultwarden-data: {}",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "compose-gitea",
    mode: "compose",
    name: "Gitea",
    description: "Git 服务模板，默认公开 Web 端口 3000。",
    tags: ["git", "stateful"],
    compose: composeDraft({
      name: "gitea",
      region: "home",
      services: [{ name: "gitea", region: "home", node: "", exposure: "tailscale-relay", domain: "git.example.com", port: "3000", publishPort: "", replicas: 1, proxy: false }],
      volumes: [{ name: "gitea-data", target: "/data", storageMode: "storageClass", storageClass: "", localNode: "", localPath: "" }],
      dockerComposeYaml: [
        "services:",
        "  gitea:",
        "    image: gitea/gitea:1.22",
        "    environment:",
        "      USER_UID: \"1000\"",
        "      USER_GID: \"1000\"",
        "    volumes:",
        "      - gitea-data:/data",
        "volumes:",
        "  gitea-data: {}",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "compose-n8n",
    mode: "compose",
    name: "n8n",
    description: "自动化工作流服务，domain 会用于 webhook URL。",
    tags: ["automation", "stateful"],
    compose: composeDraft({
      name: "n8n",
      region: "home",
      services: [{ name: "n8n", region: "home", node: "", exposure: "tailscale-relay", domain: "n8n.example.com", port: "5678", publishPort: "", replicas: 1, proxy: true }],
      volumes: [{ name: "n8n-data", target: "/home/node/.n8n", storageMode: "storageClass", storageClass: "", localNode: "", localPath: "" }],
      dockerComposeYaml: [
        "services:",
        "  n8n:",
        "    image: n8nio/n8n:latest",
        "    environment:",
        "      N8N_HOST: n8n.example.com",
        "      N8N_PORT: \"5678\"",
        "      N8N_PROTOCOL: https",
        "      WEBHOOK_URL: https://n8n.example.com/",
        "    volumes:",
        "      - n8n-data:/home/node/.n8n",
        "volumes:",
        "  n8n-data: {}",
        "",
      ].join("\n"),
    }),
  },
];
