import type { ComposeDeploymentDraft, ComposeServiceDraft, ComposeVolumeDraft, DeployTemplate, ServiceManifestDraft, ServiceVolumeDraft } from "./types";

let rowCounter = 0;
const row = (key = "", value = "") => ({ id: `row-${rowCounter++}`, key, value });
const serviceVolume = (name: string, target: string, overrides: Partial<ServiceVolumeDraft> = {}): ServiceVolumeDraft => ({
  id: `service-volume-${rowCounter++}`,
  name,
  target,
  storageMode: "unmanaged",
  storageClass: "",
  path: "",
  ...overrides,
});

export function serviceDraft(overrides: Partial<ServiceManifestDraft> = {}): ServiceManifestDraft {
  return {
    name: "whoami",
    image: "traefik/whoami:latest",
    region: "cn",
    node: "",
    exposure: "cn-edge",
    domain: "whoami.example.com",
    port: "80",
    publishPort: "",
    replicas: 1,
    proxy: false,
    env: [],
    command: "",
    volumeMounts: [],
    labels: "",
    networks: "",
    volumes: "",
    storage: "",
    cpuLimit: "",
    memoryLimit: "",
    healthcheckUrl: "",
    skipDns: false,
    skipWebhook: false,
    ...overrides,
  };
}

function composeDraft(overrides: Partial<ComposeDeploymentDraft> = {}): ComposeDeploymentDraft {
  return {
    name: "uptime-kuma",
    composeFileName: "docker-compose.yml",
    region: "home",
    services: [],
    volumes: [],
    dockerComposeYaml: "",
    skipDns: false,
    skipWebhook: false,
    ...overrides,
  };
}

function composeService(overrides: Partial<ComposeServiceDraft> & { name: string }): ComposeServiceDraft {
  const { name, ...rest } = overrides;
  return {
    name,
    region: "home",
    node: "",
    exposure: "none",
    domain: "",
    port: "",
    publishPort: "",
    replicas: 1,
    proxy: false,
    env: [],
    ...rest,
  };
}

function composeVolume(name: string, target: string, overrides: Partial<ComposeVolumeDraft> = {}): ComposeVolumeDraft {
  return {
    name,
    target,
    storageMode: "unmanaged",
    storageClass: "",
    localNode: "",
    localPath: "",
    ...overrides,
  };
}

export const DEPLOY_TEMPLATES: DeployTemplate[] = [
  {
    id: "service-custom",
    mode: "service",
    name: "自定义配置",
    description: "内部单服务起点，默认镜像 traefik/whoami。",
    tags: ["custom", "service"],
    service: serviceDraft({
      name: "custom-service",
      image: "traefik/whoami:latest",
      domain: "",
      port: "",
      exposure: "none",
    }),
  },
  {
    id: "compose-custom",
    mode: "compose",
    name: "自定义配置",
    description: "单容器 Compose 起点，默认 app 服务不暴露入口。",
    tags: ["custom", "compose"],
    compose: composeDraft({
      name: "custom-compose",
      services: [composeService({ name: "app", exposure: "none" })],
      volumes: [],
      dockerComposeYaml: [
        "services:",
        "  app:",
        "    image: traefik/whoami:latest",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "service-whoami",
    mode: "service",
    name: "whoami",
    description: "traefik/whoami，cn-edge，容器端口 80。",
    tags: ["test", "cn-edge"],
    service: serviceDraft(),
  },
  {
    id: "service-nginx",
    mode: "service",
    name: "nginx",
    description: "nginx:alpine，cn-edge，容器端口 80。",
    tags: ["web", "public"],
    service: serviceDraft({
      name: "nginx",
      image: "nginx:alpine",
      domain: "nginx.example.com",
      healthcheckUrl: "http://127.0.0.1:80/",
      cpuLimit: "0.50",
      memoryLimit: "256M",
    }),
  },
  {
    id: "service-redis-worker",
    mode: "service",
    name: "redis worker",
    description: "redis:7-alpine，内部访问，挂载 redis-data。",
    tags: ["internal", "state"],
    service: serviceDraft({
      name: "redis",
      image: "redis:7-alpine",
      exposure: "none",
      domain: "",
      port: "",
      env: [row("REDIS_ARGS", "--appendonly yes")],
      volumeMounts: [serviceVolume("redis-data", "/data")],
      memoryLimit: "256M",
    }),
  },
  {
    id: "service-grafana",
    mode: "service",
    name: "Grafana",
    description: "grafana-oss，home relay，容器端口 3000。",
    tags: ["monitoring", "dashboard"],
    service: serviceDraft({
      name: "grafana",
      image: "grafana/grafana-oss:latest",
      region: "home",
      exposure: "tailscale-relay",
      domain: "grafana.example.com",
      port: "3000",
      env: [row("GF_SERVER_ROOT_URL", "https://grafana.example.com")],
      volumeMounts: [serviceVolume("grafana-data", "/var/lib/grafana")],
      healthcheckUrl: "http://127.0.0.1:3000/api/health",
      memoryLimit: "512M",
    }),
  },
  {
    id: "service-minio",
    mode: "service",
    name: "MinIO",
    description: "minio/minio，home relay，Console 端口 9001。",
    tags: ["storage", "s3"],
    service: serviceDraft({
      name: "minio",
      image: "minio/minio:latest",
      region: "home",
      exposure: "tailscale-relay",
      domain: "minio.example.com",
      port: "9001",
      command: "server /data --console-address :9001",
      env: [
        row("MINIO_BROWSER_REDIRECT_URL", "https://minio.example.com"),
        { ...row("MINIO_ROOT_USER", "${MINIO_ROOT_USER}"), kind: "secret" },
        { ...row("MINIO_ROOT_PASSWORD", "${MINIO_ROOT_PASSWORD}"), kind: "secret" },
      ],
      volumeMounts: [serviceVolume("minio-data", "/data")],
      memoryLimit: "512M",
    }),
  },
  {
    id: "service-jellyfin",
    mode: "service",
    name: "Jellyfin",
    description: "jellyfin/jellyfin，home relay，容器端口 8096。",
    tags: ["media", "home"],
    service: serviceDraft({
      name: "jellyfin",
      image: "jellyfin/jellyfin:latest",
      region: "home",
      exposure: "tailscale-relay",
      domain: "jellyfin.example.com",
      port: "8096",
      volumeMounts: [
        serviceVolume("jellyfin-config", "/config"),
        serviceVolume("jellyfin-cache", "/cache"),
      ],
      volumes: "/srv/media:/media:ro",
      memoryLimit: "1G",
    }),
  },
  {
    id: "service-code-server",
    mode: "service",
    name: "code-server",
    description: "linuxserver/code-server，home relay，端口 8443。",
    tags: ["dev", "ide"],
    service: serviceDraft({
      name: "code-server",
      image: "lscr.io/linuxserver/code-server:latest",
      region: "home",
      exposure: "tailscale-relay",
      domain: "code.example.com",
      port: "8443",
      env: [
        row("PUID", "1000"),
        row("PGID", "1000"),
        row("TZ", "Asia/Shanghai"),
        { ...row("PASSWORD", "${CODE_SERVER_PASSWORD}"), kind: "secret" },
      ],
      volumeMounts: [
        serviceVolume("code-server-config", "/config", {
          storageMode: "storageClass",
          storageClass: "cn-nfs",
          path: "code-server/config",
        }),
      ],
      memoryLimit: "1G",
    }),
  },
  {
    id: "compose-uptime-kuma",
    mode: "compose",
    name: "Uptime Kuma",
    description: "1 个服务，home relay，容器端口 3001。",
    tags: ["monitoring", "stateful"],
    compose: composeDraft({
      name: "uptime-kuma",
      region: "home",
      services: [{ name: "uptime-kuma", region: "home", node: "", exposure: "tailscale-relay", domain: "kuma.example.com", port: "3001", publishPort: "", replicas: 1, proxy: false, env: [] }],
      volumes: [{ name: "kuma-data", target: "/app/data", storageMode: "storageClass", storageClass: "", localNode: "", localPath: "" }],
      dockerComposeYaml: [
        "services:",
        "  uptime-kuma:",
        "    image: louislam/uptime-kuma:1",
        "    volumes:",
        "      - kuma-data:/app/data",
        "volumes:",
        "  kuma-data: {}",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "compose-vaultwarden",
    mode: "compose",
    name: "Vaultwarden",
    description: "1 个服务，home relay，容器端口 80。",
    tags: ["security", "stateful"],
    compose: composeDraft({
      name: "vaultwarden",
      region: "home",
      services: [{ name: "vaultwarden", region: "home", node: "", exposure: "tailscale-relay", domain: "vault.example.com", port: "80", publishPort: "", replicas: 1, proxy: false, env: [row("WEBSOCKET_ENABLED", "true")] }],
      volumes: [{ name: "vaultwarden-data", target: "/data", storageMode: "storageClass", storageClass: "", localNode: "", localPath: "" }],
      dockerComposeYaml: [
        "services:",
        "  vaultwarden:",
        "    image: vaultwarden/server:latest",
        "    environment:",
        "      WEBSOCKET_ENABLED: \"true\"",
        "    volumes:",
        "      - vaultwarden-data:/data",
        "volumes:",
        "  vaultwarden-data: {}",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "compose-gitea",
    mode: "compose",
    name: "Gitea",
    description: "1 个服务，home relay，Web 端口 3000。",
    tags: ["git", "stateful"],
    compose: composeDraft({
      name: "gitea",
      region: "home",
      services: [{ name: "gitea", region: "home", node: "", exposure: "tailscale-relay", domain: "git.example.com", port: "3000", publishPort: "", replicas: 1, proxy: false, env: [row("USER_UID", "1000"), row("USER_GID", "1000")] }],
      volumes: [{ name: "gitea-data", target: "/data", storageMode: "storageClass", storageClass: "", localNode: "", localPath: "" }],
      dockerComposeYaml: [
        "services:",
        "  gitea:",
        "    image: gitea/gitea:1.22",
        "    environment:",
        "      USER_UID: \"1000\"",
        "      USER_GID: \"1000\"",
        "    volumes:",
        "      - gitea-data:/data",
        "volumes:",
        "  gitea-data: {}",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "compose-n8n",
    mode: "compose",
    name: "n8n",
    description: "1 个服务，home relay，Webhook URL 来自域名。",
    tags: ["automation", "stateful"],
    compose: composeDraft({
      name: "n8n",
      region: "home",
      services: [{ name: "n8n", region: "home", node: "", exposure: "tailscale-relay", domain: "n8n.example.com", port: "5678", publishPort: "", replicas: 1, proxy: true, env: [row("N8N_HOST", "n8n.example.com"), row("N8N_PORT", "5678"), row("N8N_PROTOCOL", "https"), row("WEBHOOK_URL", "https://n8n.example.com/")] }],
      volumes: [{ name: "n8n-data", target: "/home/node/.n8n", storageMode: "storageClass", storageClass: "", localNode: "", localPath: "" }],
      dockerComposeYaml: [
        "services:",
        "  n8n:",
        "    image: n8nio/n8n:latest",
        "    environment:",
        "      N8N_HOST: n8n.example.com",
        "      N8N_PORT: \"5678\"",
        "      N8N_PROTOCOL: https",
        "      WEBHOOK_URL: https://n8n.example.com/",
        "    volumes:",
        "      - n8n-data:/home/node/.n8n",
        "volumes:",
        "  n8n-data: {}",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "compose-nextcloud",
    mode: "compose",
    name: "Nextcloud",
    description: "3 个服务：nextcloud、postgres、redis。",
    tags: ["files", "collaboration"],
    compose: composeDraft({
      name: "nextcloud",
      region: "home",
      services: [
        composeService({
          name: "nextcloud",
          exposure: "tailscale-relay",
          domain: "cloud.example.com",
          port: "80",
          env: [
            row("POSTGRES_HOST", "postgres"),
            row("POSTGRES_DB", "nextcloud"),
            row("POSTGRES_USER", "nextcloud"),
            row("REDIS_HOST", "redis"),
            { ...row("POSTGRES_PASSWORD", "${NEXTCLOUD_DB_PASSWORD}"), kind: "secret" },
            { ...row("NEXTCLOUD_ADMIN_USER", "${NEXTCLOUD_ADMIN_USER}"), kind: "secret" },
            { ...row("NEXTCLOUD_ADMIN_PASSWORD", "${NEXTCLOUD_ADMIN_PASSWORD}"), kind: "secret" },
          ],
        }),
        composeService({
          name: "postgres",
          env: [
            row("POSTGRES_DB", "nextcloud"),
            row("POSTGRES_USER", "nextcloud"),
            { ...row("POSTGRES_PASSWORD", "${NEXTCLOUD_DB_PASSWORD}"), kind: "secret" },
          ],
        }),
        composeService({ name: "redis" }),
      ],
      volumes: [
        composeVolume("nextcloud-data", "/var/www/html", { storageMode: "storageClass" }),
        composeVolume("nextcloud-db", "/var/lib/postgresql/data", { storageMode: "storageClass" }),
      ],
      dockerComposeYaml: [
        "services:",
        "  nextcloud:",
        "    image: nextcloud:apache",
        "    environment:",
        "      POSTGRES_HOST: postgres",
        "      POSTGRES_DB: nextcloud",
        "      POSTGRES_USER: nextcloud",
        "      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}",
        "      REDIS_HOST: redis",
        "      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}",
        "      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}",
        "    volumes:",
        "      - nextcloud-data:/var/www/html",
        "    depends_on:",
        "      - postgres",
        "      - redis",
        "  postgres:",
        "    image: postgres:16-alpine",
        "    environment:",
        "      POSTGRES_DB: nextcloud",
        "      POSTGRES_USER: nextcloud",
        "      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}",
        "    volumes:",
        "      - nextcloud-db:/var/lib/postgresql/data",
        "  redis:",
        "    image: redis:7-alpine",
        "volumes:",
        "  nextcloud-data: {}",
        "  nextcloud-db: {}",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "compose-ghost",
    mode: "compose",
    name: "Ghost",
    description: "2 个服务：ghost、mysql，端口 2368。",
    tags: ["blog", "cms"],
    compose: composeDraft({
      name: "ghost",
      region: "home",
      services: [
        composeService({
          name: "ghost",
          exposure: "tailscale-relay",
          domain: "blog.example.com",
          port: "2368",
          env: [
            row("url", "https://blog.example.com"),
            row("database__client", "mysql"),
            row("database__connection__host", "mysql"),
            row("database__connection__user", "ghost"),
            row("database__connection__database", "ghost"),
            { ...row("database__connection__password", "${GHOST_DB_PASSWORD}"), kind: "secret" },
          ],
        }),
        composeService({
          name: "mysql",
          env: [
            row("MYSQL_DATABASE", "ghost"),
            row("MYSQL_USER", "ghost"),
            { ...row("MYSQL_PASSWORD", "${GHOST_DB_PASSWORD}"), kind: "secret" },
            { ...row("MYSQL_ROOT_PASSWORD", "${GHOST_MYSQL_ROOT_PASSWORD}"), kind: "secret" },
          ],
        }),
      ],
      volumes: [
        composeVolume("ghost-content", "/var/lib/ghost/content", { storageMode: "storageClass" }),
        composeVolume("ghost-mysql", "/var/lib/mysql", { storageMode: "storageClass" }),
      ],
      dockerComposeYaml: [
        "services:",
        "  ghost:",
        "    image: ghost:5-alpine",
        "    environment:",
        "      url: https://blog.example.com",
        "      database__client: mysql",
        "      database__connection__host: mysql",
        "      database__connection__user: ghost",
        "      database__connection__password: ${GHOST_DB_PASSWORD}",
        "      database__connection__database: ghost",
        "    volumes:",
        "      - ghost-content:/var/lib/ghost/content",
        "    depends_on:",
        "      - mysql",
        "  mysql:",
        "    image: mysql:8",
        "    environment:",
        "      MYSQL_DATABASE: ghost",
        "      MYSQL_USER: ghost",
        "      MYSQL_PASSWORD: ${GHOST_DB_PASSWORD}",
        "      MYSQL_ROOT_PASSWORD: ${GHOST_MYSQL_ROOT_PASSWORD}",
        "    volumes:",
        "      - ghost-mysql:/var/lib/mysql",
        "volumes:",
        "  ghost-content: {}",
        "  ghost-mysql: {}",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "compose-paperless-ngx",
    mode: "compose",
    name: "Paperless-ngx",
    description: "3 个服务：paperless、postgres、redis。",
    tags: ["documents", "ocr"],
    compose: composeDraft({
      name: "paperless",
      region: "home",
      services: [
        composeService({
          name: "paperless",
          exposure: "tailscale-relay",
          domain: "paperless.example.com",
          port: "8000",
          env: [
            row("PAPERLESS_REDIS", "redis://redis:6379"),
            row("PAPERLESS_DBHOST", "postgres"),
            row("PAPERLESS_DBNAME", "paperless"),
            row("PAPERLESS_DBUSER", "paperless"),
            row("PAPERLESS_URL", "https://paperless.example.com"),
            { ...row("PAPERLESS_DBPASS", "${PAPERLESS_DB_PASSWORD}"), kind: "secret" },
            { ...row("PAPERLESS_SECRET_KEY", "${PAPERLESS_SECRET_KEY}"), kind: "secret" },
          ],
        }),
        composeService({ name: "redis" }),
        composeService({
          name: "postgres",
          env: [
            row("POSTGRES_DB", "paperless"),
            row("POSTGRES_USER", "paperless"),
            { ...row("POSTGRES_PASSWORD", "${PAPERLESS_DB_PASSWORD}"), kind: "secret" },
          ],
        }),
      ],
      volumes: [
        composeVolume("paperless-data", "/usr/src/paperless/data", { storageMode: "storageClass" }),
        composeVolume("paperless-media", "/usr/src/paperless/media", { storageMode: "storageClass" }),
        composeVolume("paperless-db", "/var/lib/postgresql/data", { storageMode: "storageClass" }),
      ],
      dockerComposeYaml: [
        "services:",
        "  paperless:",
        "    image: ghcr.io/paperless-ngx/paperless-ngx:latest",
        "    environment:",
        "      PAPERLESS_REDIS: redis://redis:6379",
        "      PAPERLESS_DBHOST: postgres",
        "      PAPERLESS_DBNAME: paperless",
        "      PAPERLESS_DBUSER: paperless",
        "      PAPERLESS_DBPASS: ${PAPERLESS_DB_PASSWORD}",
        "      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}",
        "      PAPERLESS_URL: https://paperless.example.com",
        "    volumes:",
        "      - paperless-data:/usr/src/paperless/data",
        "      - paperless-media:/usr/src/paperless/media",
        "    depends_on:",
        "      - redis",
        "      - postgres",
        "  redis:",
        "    image: redis:7-alpine",
        "  postgres:",
        "    image: postgres:16-alpine",
        "    environment:",
        "      POSTGRES_DB: paperless",
        "      POSTGRES_USER: paperless",
        "      POSTGRES_PASSWORD: ${PAPERLESS_DB_PASSWORD}",
        "    volumes:",
        "      - paperless-db:/var/lib/postgresql/data",
        "volumes:",
        "  paperless-data: {}",
        "  paperless-media: {}",
        "  paperless-db: {}",
        "",
      ].join("\n"),
    }),
  },
  {
    id: "compose-stirling-pdf",
    mode: "compose",
    name: "Stirling PDF",
    description: "1 个服务，home relay，容器端口 8080。",
    tags: ["documents", "utility"],
    compose: composeDraft({
      name: "stirling-pdf",
      region: "home",
      services: [
        composeService({
          name: "stirling-pdf",
          exposure: "tailscale-relay",
          domain: "pdf.example.com",
          port: "8080",
          env: [row("DOCKER_ENABLE_SECURITY", "false")],
        }),
      ],
      volumes: [
        composeVolume("stirling-training-data", "/usr/share/tessdata"),
        composeVolume("stirling-configs", "/configs"),
      ],
      dockerComposeYaml: [
        "services:",
        "  stirling-pdf:",
        "    image: frooodle/s-pdf:latest",
        "    environment:",
        "      DOCKER_ENABLE_SECURITY: \"false\"",
        "    volumes:",
        "      - stirling-training-data:/usr/share/tessdata",
        "      - stirling-configs:/configs",
        "volumes:",
        "  stirling-training-data: {}",
        "  stirling-configs: {}",
        "",
      ].join("\n"),
    }),
  },
];
