#!/usr/bin/env python3
"""Render the public argparse tree without invoking any CLI command or loading secrets."""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from luma.cli import build_parser


def public_parsers(parser: argparse.ArgumentParser):
    """Walk public commands in registration order, omitting hidden agent internals."""
    yield parser
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        hidden = {
            choice.dest for choice in action._choices_actions
            if choice.help == argparse.SUPPRESS
        }
        # The CLI removes hidden choices from its help metadata, and supplies an
        # explicit public metavar instead. Respect that list as well.
        visible = None
        if action.metavar and action.metavar.startswith("{") and action.metavar.endswith("}"):
            visible = set(action.metavar[1:-1].split(","))
        for name, child in action.choices.items():
            if name not in hidden and (visible is None or name in visible):
                yield from public_parsers(child)


def render_reference() -> str:
    parsers = list(public_parsers(build_parser()))
    lines = [
        "# Luma CLI command reference",
        "",
        "<!-- Generated by scripts/generate-cli-reference.py; do not edit by hand. -->",
        "",
        "Generated from the current CLI parser. Regenerate with",
        "`python scripts/generate-cli-reference.py`; CI verifies it with `--check`.",
        "See [the CLI guide](luma-cli.md) for authentication, deployment and recovery workflows.",
        "Global options precede the command; command options follow the command shown below.",
        "",
    ]
    for parser in parsers:
        # Usage wrapping changed between Python 3.12 and 3.13. Keep it on one
        # line, and use fixed-width argument details independent of COLUMNS.
        usage = argparse.HelpFormatter(parser.prog, width=10000)
        usage.add_usage(parser.usage, parser._actions, parser._mutually_exclusive_groups)
        formatter = argparse.HelpFormatter(parser.prog, width=100)
        formatter.add_text(parser.description)
        for group in parser._action_groups:
            visible = [action for action in group._group_actions if action.help != argparse.SUPPRESS]
            if not visible:
                continue
            formatter.start_section("arguments")
            formatter.add_arguments(visible)
            formatter.end_section()
        help_text = usage.format_help().rstrip() + "\n\n" + formatter.format_help().rstrip()
        lines.extend([f"## `{parser.prog}`", "", "```text", help_text, "```", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in reference is stale")
    args = parser.parse_args()
    output = ROOT / "docs" / "luma-cli-reference.md"
    expected = render_reference()
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != expected:
            print("CLI reference is stale. Run: python scripts/generate-cli-reference.py", file=sys.stderr)
            return 1
        return 0
    output.write_text(expected, encoding="utf-8")
    print(output.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
