#!/usr/bin/env python3
"""Render the public argparse tree without invoking any CLI command or loading secrets."""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from luma.cli import build_parser


def public_parsers(parser: argparse.ArgumentParser):
    """Walk public commands in registration order, omitting hidden agent internals."""
    yield parser
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        # Public commands are registered with a help summary; internal entry
        # points such as node-agent are not.
        visible = {choice.dest for choice in action._choices_actions if choice.help != argparse.SUPPRESS}
        for name, child in action.choices.items():
            if name in visible:
                yield from public_parsers(child)


HEADERS = {
    "luma-cli-reference.md": [
        "# Luma CLI command reference",
        "",
        "<!-- Generated by scripts/generate-cli-reference.py; do not edit by hand. -->",
        "",
        "Generated from the current CLI parser. Regenerate with",
        "`python scripts/generate-cli-reference.py`; CI verifies it with `--check`.",
        "For task-oriented walkthroughs see [Getting started](getting-started.md),",
        "[Deploying applications](deploying.md) and [Operations](operations.md).",
        "Global options precede the command; command options follow the command shown below.",
        "",
    ],
    "luma-cli-reference.zh-CN.md": [
        "# Luma CLI 命令参考 {#luma-cli-command-reference}",
        "",
        "<!-- 由 scripts/generate-cli-reference.py 生成，请勿手动编辑。 -->",
        "",
        "本页由当前 CLI 解析器自动生成，帮助文本保持英文原样，便于与终端输出逐项核对。",
        "使用 `python scripts/generate-cli-reference.py` 重新生成，CI 通过 `--check` 校验。",
        "按任务组织的说明见[快速上手](getting-started.zh-CN.md)、[部署应用](deploying.zh-CN.md)和[日常运维](operations.zh-CN.md)。",
        "全局选项写在命令之前，命令选项写在命令之后。",
        "",
    ],
}


def render_reference(header: list[str] | None = None) -> str:
    parsers = list(public_parsers(build_parser()))
    lines = list(header or HEADERS["luma-cli-reference.md"])
    for parser in parsers:
        # Usage wrapping changed between Python 3.12 and 3.13. Keep it on one
        # line, and use fixed-width argument details independent of COLUMNS.
        usage = argparse.HelpFormatter(parser.prog, width=10000)
        usage.add_usage(parser.usage, parser._actions, parser._mutually_exclusive_groups)
        formatter = parser.formatter_class(parser.prog, width=100)
        formatter.add_text(parser.description)
        for group in parser._action_groups:
            visible = [action for action in group._group_actions if action.help != argparse.SUPPRESS]
            if not visible:
                continue
            formatter.start_section("arguments")
            formatter.add_arguments(visible)
            formatter.end_section()
        formatter.add_text(parser.epilog)
        help_text = usage.format_help().rstrip() + "\n\n" + formatter.format_help().rstrip()
        lines.extend([f"## `{parser.prog}`", "", "```text", help_text, "```", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in reference is stale")
    args = parser.parse_args()
    stale = False
    for name, header in HEADERS.items():
        output = ROOT / "docs" / name
        expected = render_reference(header)
        if args.check:
            if not output.exists() or output.read_text(encoding="utf-8") != expected:
                stale = True
            continue
        output.write_text(expected, encoding="utf-8")
        print(output.relative_to(ROOT))
    if stale:
        print("CLI reference is stale. Run: python scripts/generate-cli-reference.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
