#!/usr/bin/env bash
# Install the private AI-controller handoff generated by the LAE staging bundle.
set -Eeuo pipefail
umask 077

[[ ${EUID} -eq 0 ]] || { echo "run as root" >&2; exit 2; }
[[ $# -eq 1 ]] || { echo "usage: $0 /path/to/builder-agent-ai.env" >&2; exit 2; }
source_file=$1
[[ -f "$source_file" && ! -L "$source_file" ]] || { echo "invalid builder AI env" >&2; exit 2; }
[[ $(stat -c %a "$source_file") =~ ^(400|600)$ ]] || { echo "builder AI env must be mode 0400 or 0600" >&2; exit 2; }

python3 - "$source_file" <<'PY'
import re, sys
from pathlib import Path
values = {}
for line in Path(sys.argv[1]).read_text(encoding="utf-8").splitlines():
    if line and not line.startswith("#") and "=" in line:
        key, value = line.split("=", 1)
        values[key] = value
expected = {"LUMA_BUILDER_ANALYZE_AI_REQUIRED", "LUMA_BUILDER_ANALYZE_CONTROLLER_TOKEN", "LUMA_BUILDER_ANALYZE_CONTROLLER_URL"}
if set(values) != expected:
    raise SystemExit("builder AI env has an invalid closed key set")
if values["LUMA_BUILDER_ANALYZE_AI_REQUIRED"] != "1":
    raise SystemExit("staging Builder must require AI diagnostics")
if not values["LUMA_BUILDER_ANALYZE_CONTROLLER_URL"].startswith("https://"):
    raise SystemExit("controller URL must use HTTPS")
if not re.fullmatch(r"lae_agent_[A-Za-z0-9_-]{32,}", values["LUMA_BUILDER_ANALYZE_CONTROLLER_TOKEN"]):
    raise SystemExit("controller token is invalid")
PY

install -d -m 0755 /etc/luma /etc/systemd/system/luma-node-agent.service.d
install -m 0600 -o root -g root "$source_file" /etc/luma/lae-builder-ai.env
temporary=$(mktemp)
trap 'rm -f "$temporary"' EXIT
printf '%s\n' '[Service]' 'EnvironmentFile=/etc/luma/lae-builder-ai.env' >"$temporary"
install -m 0644 -o root -g root "$temporary" /etc/systemd/system/luma-node-agent.service.d/lae-agent-ai.conf
systemctl daemon-reload
systemctl restart luma-node-agent.service
systemctl is-active --quiet luma-node-agent.service
echo "LAE Builder AI controller handoff installed"
